version: "3.2"
services:
  postgres:
    image: postgres
    ports: 
     - 5432:5432
    environment:
      POSTGRES_DB: "testdb"
      POSTGRES_PASSWORD: "password"
      POSTGRES_USER: "user"
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    ports:
      - 27017:27017